### ISSUE TITLE
why I need firebase if I use Parse?

### ISSUE THREAD

**Issue by kalitas** [relatedcode/EncryptedChat#118]

**Comment by sidan5** [comment]
+1
We already have parse only chat and it's not logical to have fire base also (reduce capacity)

**Comment by relatedcode** [comment]
Firebase is needed for realtime actions like:

- Typing indicator
- Message delivery receipt
- Message read receipt

and of course to send and receive messages in real time.

If you need a Parse only solution, please check https://github.com/relatedcode/ParseChat
